- name: playbook to deploy mcaptcha with postgres db and custom redis cache.
  hosts: all
  tasks:
  - name: copy mcaptcha docker-compose
    copy:
      src: mcaptcha/docker-compose.yml
      dest: docker-composes/mcaptcha/
  - name: deploy the docker-compose
    docker_compose:
      project_src: docker-composes/mcaptcha/
      state: present
