version: '3.9'

services:
  mcaptcha:
    image: mcaptcha/mcaptcha-dos-server:latest
    ports:
      - 5000:5000
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/postgres # change password
      MCAPTCHA_REDIS_URL: redis://mcaptcha-redis/
      RUST_LOG: debug
    restart: unless-stopped

  postgres:
    image: postgres:13.2
    volumes:
      - mcaptcha-dos-data:/var/lib/postgresql/
    environment:
      POSTGRES_PASSWORD: password # change password
      PGDATA: /var/lib/postgresql/data/mcaptcha/
    restart: unless-stopped

volumes:
  mcaptcha-dos-data:
