- name: playbook to deploy a custom built locust node to test a unprotected instance.
  hosts: all
  tasks:
  - name: copy locust-unprotected docker-compose
    copy:
      src: unprotected-locust/docker-compose.yml
      dest: docker-composes/unprotected-node/
  - name: deploy the docker-compose
    docker_compose:
      project_src: docker-composes/unprotected-node/
      state: present
