- name: playbook to deploy a custom built locust node to test a protected instance.
  hosts: all
  tasks:
  - name: copy protected-node docker-compose
    copy:
      src: protected-node/docker-compose.yml
      dest: docker-composes/protected-node/
  - name: deploy the docker-compose
    docker_compose:
      project_src: docker-composes/protected-node/
      state: present
